name: borrow_books
description: A new flutter module project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  ovprogresshud: ^0.2.1
  flustars: ^0.2.5
  common_utils: ^1.1.1
  intro_slider: ^1.2.0
  qr_flutter: ^1.1.6
  # qson_util:
  #   path: ../lib/util/

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  assets:
    - images/tab_home.png
    - images/tab_cate.png
    - images/tab_me.png
    - images/home_banner.png
    - images/home_action1.png
    - images/home_action2.png
    - images/home_action3.png
    - images/home_rec_title.png
    - images/item_like.png
    - images/item_un_like.png
    - images/item_fav.png
    - images/item_unFav.png
    - images/nav_back.png
    - images/arrow_gray.png
    - images/def_icon.png
    - images/log_out.png
    - images/login_icon.png
    - images/login_bj.png
    - images/qr.png

    - images/intro_01.png
    - images/intro_02.png
    - images/intro_03.png
    - images/intro_04.png

    - images/item_reserve.png
    - images/list_image_1.png
    - images/list_image_2.png
    - images/list_image_3.png
    - images/list_image_4.png
    - images/list_image_5.png
    - images/list_image_6.png
    - images/list_image_7.png
    - images/list_image_8.png
    - images/list_image_9.png
    - images/list_image_10.png
    - images/list_image_11.png
    - images/list_image_12.png
    - images/list_image_13.png
    - images/list_image_14.png
    - images/list_image_15.png

    - images/cate_list_1.png
    - images/cate_list_2.png
    - images/cate_list_3.png
    - images/cate_list_4.png
    - images/cate_list_5.png
    - images/cate_list_6.png
    - images/cate_list_7.png
    - images/cate_list_8.png
    - images/cate_list_9.png
    - images/cate_list_10.png

    - images/me_jieshu.png
    - images/me_gywm.png
    - images/me_wddz.png
    - images/me_wdll.png
    - images/me_wdmp.png
    - images/me_wdsc.png
    - images/me_wdsz.png

    - data/home_list.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidPackage: com.example.borrow_books
    iosBundleIdentifier: com.example.borrow_books
